import { SetMetadata } from '@nestjs/common';

export enum AuditActionType {
  CANCEL_ORDER = 'CANCEL_ORDER',
  UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS',

  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  ARCHIVE_PRODUCT = 'ARCHIVE_PRODUCT',
  RESTORE_ARCHIVED_PRODUCT = 'RESTORE_ARCHIVED_PRODUCT',
  RESTORE_DELETED_PRODUCT = 'RESTORE_DELETED_PRODUCT',
}

export const AUDIT_ACTION_KEY = 'audit_action';

export const AuditAction = (action: AuditActionType) =>
  SetMetadata(AUDIT_ACTION_KEY, action);
